# 5. Data Structures

## 5.1. More on Lists

- ```list.append(x)``` - Add an item to the end of the list.
- ```list.extend(iterable)``` - Extend the list by appending all the items from the iterable.
- ```list.insert(i, x)``` - Insert an item at a given position.
- ```list.remove(x)``` - Remove the first item from the list whose value is equal to x.
- ```list.pop([i])``` - Remove the item at the given position in the list, and return it. If no index is specified, a.pop() removes and returns the last item in the list.
- ```list.clear()``` - Remove all items from the list.
- ```list.index(x[, start[, end]])``` - Return zero-based index in the list of the first item whose value is equal to x. Raises a ValueError if there is no such item.
- ```list.count(x)``` - Return the number of times x appears in the list.
- ```list.sort(*, key=None, reverse=False)``` - Sort the items of the list in place.
- ```list.reverse()``` - Reverse the elements of the list in place.
- ```list.copy()``` - Return a shallow copy of the list.

In [7]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
print(fruits)
print(fruits.count('apple'))
print(fruits.count('tangerine'))
print(fruits.index('banana'))
print(fruits.index('banana', 4))
fruits.reverse()
print(fruits)
fruits.append('grape')
print(fruits)
fruits.sort()
print(fruits)
print(fruits.pop())
print(fruits)

['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
2
0
3
6
['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']
['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']
['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']
pear
['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange']


You might have noticed that methods like ```insert```, ```remove``` or ```sort``` that only modify the list have no return value printed – they return the default ```None```. 1 This is a design principle for all mutable data structures in Python.

### 5.1.1. Using Lists as Stacks

The list methods make it very easy to use a list as a stack, where the last element added is the first element retrieved (“last-in, first-out”). To add an item to the top of the stack, use ```append()```. To retrieve an item from the top of the stack, use ```pop()``` without an explicit index. For example:

In [12]:
stack = [3, 4, 5]
print(stack)
stack.append(6)
stack.append(7)
print(stack)
stack.pop()
print(stack)

[3, 4, 5]
[3, 4, 5, 6, 7]
[3, 4, 5, 6]


### 5.1.2. Using Lists as Queues

It is also possible to use a list as a queue, where the first element added is the first element retrieved (“**first-in, first-out**”); however, lists are not efficient for this purpose. While appends and pops from the end of list are fast, doing inserts or pops from the beginning of a list is slow (because all of the other elements have to be shifted by one).

To implement a queue, use [collections.deque](https://docs.python.org/3/library/collections.html#collections.deque) which was designed to have fast appends and pops from both ends. For example:

In [17]:
from collections import deque
queue = deque(["Eric", "John", "Michael"])
print(queue)
queue.append("Terry")           # Terry arrives
queue.append("Graham")          # Graham arrives
print(queue)
print(queue.popleft())
print(queue.popleft())
print(queue)                    # Remaining queue in order of arrival

deque(['Eric', 'John', 'Michael'])
deque(['Eric', 'John', 'Michael', 'Terry', 'Graham'])
Eric
John
deque(['Michael', 'Terry', 'Graham'])


### 5.1.3. List Comprehensions

List comprehensions provide a concise way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence or iterable, or to create a subsequence of those elements that satisfy a certain condition.

In [1]:
squares = []
for x in range(10):
    squares.append(x**2)

print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Note that this creates (or overwrites) a variable named ```x``` that still exists after the loop completes. We can calculate the list of squares without any side effects using:

In [1]:
squares = list(map(lambda x: x**2, range(10)))
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [3]:
squares = [x**2 for x in range(10)] # more concise and readable
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


A list comprehension consists of brackets containing an expression followed by a for clause, then zero or more ```for``` or ```if``` clauses. The result will be a new list resulting from evaluating the expression in the context of the for and if clauses which follow it. For example, this listcomp combines the elements of two lists if they are not equal:

In [4]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

and it’s equivalent to:

In [5]:
combs = []
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x, y))
            
combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

If the expression is a tuple (e.g. the ```(x, y)``` in the previous example), it must be parenthesized.

In [11]:
vec = [-4, -2, 0, 2, 4] # create a new list with the values doubled
print(vec)
print([x*2 for x in vec])
print([x for x in vec if x >= 0]) # filter the list to exclude negative numbers
print([abs(x) for x in vec])

[-4, -2, 0, 2, 4]
[-8, -4, 0, 4, 8]
[0, 2, 4]
[4, 2, 0, 2, 4]


In [14]:
freshfruit = ['  banana', '  loganberry ', 'passion fruit  '] # call a method on each element
print(freshfruit)
print([weapon.strip() for weapon in freshfruit])

['  banana', '  loganberry ', 'passion fruit  ']
['banana', 'loganberry', 'passion fruit']


In [17]:
# create a list of 2-tuples like (number, square)
print([(x, x**2) for x in range(6)])
# the tuple must be parenthesized, otherwise an error is raised

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]


In [19]:
# flatten a list using a listcomp with two 'for'
vec = [[1,2,3], [4,5,6], [7,8,9]]
print(vec)
print([num for elem in vec for num in elem])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [20]:
from math import pi
print([str(round(pi, i)) for i in range(1, 6)])

['3.1', '3.14', '3.142', '3.1416', '3.14159']


### 5.1.4. Nested List Comprehensions

The initial expression in a list comprehension can be any arbitrary expression, including another list comprehension.

In [2]:
matrix = [
     [1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
]

# list comprehension will transpose rows and columns:
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [3]:
transposed = []
for i in range(4):
     transposed.append([row[i] for row in matrix])
        
transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [8]:
transposed = []
for i in range(4):
    # the following 3 lines implement the nested listcomp
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
        transposed.append(transposed_row)
    
transposed

[[1, 5, 9],
 [1, 5, 9],
 [1, 5, 9],
 [2, 6, 10],
 [2, 6, 10],
 [2, 6, 10],
 [3, 7, 11],
 [3, 7, 11],
 [3, 7, 11],
 [4, 8, 12],
 [4, 8, 12],
 [4, 8, 12]]

In the real world, you should prefer built-in functions to complex flow statements. The zip() (make an iterator that aggregates elements from each of the iterables.) function would do a great job for this use case:    

In [9]:
list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

### 5.2. The del statement

There is a way to remove an item from a list given its index instead of its value: the ```del``` statement. This differs from the ```pop()``` method which returns a value. The ```del``` statement can also be used to remove slices from a list or clear the entire list.

In [15]:
a = [-1, 1, 66.25, 333, 333, 1234.5]
del a[0]
print(a)
del a[2:4] # 2 included and 4 excluded
print(a)
del a[:]
print(a)
# del a delete entire variables

[1, 66.25, 333, 333, 1234.5]
[1, 66.25, 1234.5]
[]


## 5.3. Tuples and Sequences

 They are two examples of sequence data types (see Sequence Types — list, tuple, range). Since Python is an evolving language, other sequence data types may be added. There is also another standard **sequence data type**: the tuple. A tuple consists of a number of values separated by commas, for instance:

In [2]:
t = 12345, 54321, 'hello!'
print(t[0])
print(t)
u = t, (1, 2, 3, 4, 5)
print(u)

# t[0] = 99999 ERROR! Tuples are immutable
# but they can contain mutable objects
v = ([1, 2, 3], [3, 2, 1])
print(v)

12345
(12345, 54321, 'hello!')
((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))
([1, 2, 3], [3, 2, 1])


As you see, on output tuples are **always enclosed in parentheses**, so that nested tuples are interpreted correctly; they may be input with or without surrounding parentheses, although often parentheses are necessary anyway (if the tuple is part of a larger expression). It is not possible to assign to the individual items of a tuple, however it is possible to create tuples which contain mutable objects, such as lists.

Though tuples may seem similar to lists, they are often used in different situations and for different purposes. **Tuples are immutable**, and usually contain a **heterogeneous sequence of elements** that are **accessed via unpacking** or indexing. **Lists are mutable**, and their elements are usually **homogeneous** and are **accessed by iterating over the list**.

A special problem is the construction of tuples containing **0 or 1 items**: the syntax has some extra quirks to accommodate these. Empty tuples are constructed by an empty pair of parentheses; a tuple with one item is constructed by following a value with a comma.

In [3]:
empty = ()
singleton = 'hello', # <- note comma
print(len(empty))
print(len(singleton))
print(singleton)

0
1
('hello',)


The statement ```t = 12345, 54321, 'hello!'``` is an example of tuple packing: the values ```12345```, ```54321``` and ```'hello!'``` are packed together in a tuple. The reverse operation is also possible:

In [10]:
x, y, z = t
print(t)
print(x)
print(y)
print(z)

(12345, 54321, 'hello!')
12345
54321
hello!


This is called, appropriately enough, sequence unpacking and works for any sequence on the right-hand side. Sequence unpacking requires that there are as many variables on the left side of the equals sign as there are elements in the sequence. Note that multiple assignment is really just a combination of tuple packing and sequence unpacking.

## 5.4. Sets

Python also includes a data type for ```sets```. A set is an **unordered collection with no duplicate elements**. **Basic uses include membership testing and eliminating duplicate entries**. Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.

Curly braces or the ```set()``` function can be used to create sets. Note: to create an empty set you have to use ```set()```, not ```{}```; the latter creates an empty dictionary, a data structure that we discuss in the next section.

In [17]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)
print('orange' in basket)
print('crabgrass' in basket)

# Demonstrate set operations on unique letters from two words
a = set('abracadabra')
b = set('alacazam')
print(a)     # unique letters in a
print(a - b) # letters in a but not in b
print(a | b) # letters in a or b or both
print(a & b) # letters in both a and b
print(a ^ b) # letters in a or b but not both

{'orange', 'pear', 'apple', 'banana'}
True
False
{'r', 'c', 'b', 'a', 'd'}
{'d', 'b', 'r'}
{'m', 'l', 'r', 'c', 'b', 'z', 'a', 'd'}
{'c', 'a'}
{'d', 'z', 'b', 'r', 'l', 'm'}


Similarly to list comprehensions, set comprehensions are also supported:

In [18]:
a = {x for x in 'abracadabra' if x not in 'abc'}
print(a)

{'d', 'r'}


## 5.5. Dictionaries

Dictionaries are sometimes found in other languages as “associative memories” or “associative arrays”. Unlike sequences, which are indexed by a range of numbers, dictionaries are **indexed by keys**, which can be any **immutable type**; strings and numbers can always be keys. Tuples can be used as keys if they contain only strings, numbers, or tuples; if a tuple contains any mutable object either directly or indirectly, it cannot be used as a key. You can’t use lists as keys, since lists can be modified in place using index assignments, slice assignments, or methods like ```append()``` and ```extend()```.

It is best to think of a dictionary as a set of key: value pairs, with the requirement that the keys are unique (within one dictionary). A pair of braces creates an empty dictionary: ```{}```. Placing a comma-separated list of key:value pairs within the braces adds initial key:value pairs to the dictionary; this is also the way dictionaries are written on output.

The main operations on a dictionary are storing a value with some key and extracting the value given the key. It is also possible to delete a key:value pair with ```del```. If you store using a key that is already in use, the old value associated with that key is forgotten. It is an error to extract a value using a non-existent key.

Performing ```list(d)``` on a dictionary returns a list of all the keys used in the dictionary, in insertion order (if you want it sorted, just use ```sorted(d)``` instead). To check whether a single key is in the dictionary, use the ```in``` keyword.

In [22]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
print(tel)
print(tel['jack'])
del tel['sape']
tel['ivr'] = 4127
print(tel)
print(sorted(tel))
print('guido' in tel)
print('jack' not in tel)

{'jack': 4098, 'sape': 4139, 'guido': 4127}
4098
{'jack': 4098, 'guido': 4127, 'ivr': 4127}
['guido', 'ivr', 'jack']
True
False


In [23]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)]) # dict constructor

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [24]:
 {x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

In [25]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

## 5.6. Looping Techniques

When looping through dictionaries, the key and corresponding value can be retrieved at the same time using the ```items()``` method.

In [27]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k, v)

gallahad the pure
robin the brave


In [28]:
for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

0 tic
1 tac
2 toe


To loop over two or more sequences at the same time, the entries can be paired with the ```zip()``` function.

In [29]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q, a in zip(questions, answers):
    print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


To loop over a sequence in reverse, first specify the sequence in a forward direction and then call the ```reversed()``` function.

In [30]:
for i in reversed(range(1, 10, 2)):
    print(i)

9
7
5
3
1


To loop over a sequence in sorted order, use the ```sorted()``` function which returns a new sorted list while leaving the source unaltered.

In [31]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for f in sorted(set(basket)):
    print(f)

apple
banana
orange
pear


It is sometimes tempting to change a list while you are looping over it; however, it is often simpler and safer to create a new list instead.

In [33]:
import math
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]
filtered_data = []
for value in raw_data:
    if not math.isnan(value):
        filtered_data.append(value)
        
print(filtered_data)

[56.2, 51.7, 55.3, 52.5, 47.8]


## 5.7. More on Conditions

The conditions used in ```while``` and ```if``` statements can contain any operators, not just comparisons.

The comparison operators ```in``` and ```not in``` check whether a value occurs (does not occur) in a sequence. The operators ```is``` and ```is not``` compare whether two objects are really the same object;

...

In [34]:
string1, string2, string3 = '', 'Trondheim', 'Hammer Dance'
non_null = string1 or string2 or string3
print(non_null)

Trondheim


## 5.8. Comparing Sequences and Other Types

...

In [37]:
print((1, 2, 3)              < (1, 2, 4))
print([1, 2, 3]              < [1, 2, 4])
print('ABC' < 'C' < 'Pascal' < 'Python')
print((1, 2, 3, 4)           < (1, 2, 4))
print((1, 2)                 < (1, 2, -1))
print((1, 2, 3)             == (1.0, 2.0, 3.0))
print((1, 2, ('aa', 'ab'))   < (1, 2, ('abc', 'a'), 4))

True
True
True
True
True
True
True
